volumes:
    postgres:
    erp:
    etc:
    addons:
    mariadb:
    npm:    
    letsencrypt:
    duckdns:
    
networks:
    backend:
    
services:
  db:
    image: postgres:13
    container_name: db
    user: root
    networks:
      - backend
    hostname: db
    environment:
      - POSTGRES_PASSWORD=erp
      - POSTGRES_USER=erp
      - POSTGRES_DB=postgres
    restart: always
    volumes:
        - postgres:/var/lib/postgresql/data

  erp:
    image: fbieringer/odoo:14.0-arm64
    #image: wbms/odoo-14.0:20220413
    container_name: erp
    user: root
    networks:
      backend:
      bridge:
    hostname: erp
    ports:
      - "8069:8069"
      - "8071:8071"
      - "8072:8072"
    tty: true
    command: --
    environment:
      - HOST=db
      - USER=erp
      - PASSWORD=erp
    volumes:
      - erp:/var/lib/odoo
      - addons:/mnt/extra-addons
      - etc:/etc/odoo
    restart: always
    depends_on:
      - db

  mariadb:
    image: 'jc21/mariadb-aria:latest'
    container_name: mariadb
    networks:
      backend:
    hostname: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: "npm"
      MYSQL_DATABASE: "npm"
      MYSQL_USER: "npm"
      MYSQL_PASSWORD: "npm"
    volumes:
      - mariadb:/var/lib/mysql
    restart: unless-stopped
        
  npm:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: npm
    networks:
      backend:
      bridge:
    hostname: npm
    ports:
      - "80:80"
      - "443:443"
      - "81:81"
    environment:
      DB_MYSQL_HOST: "mariadb"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "npm"
      DB_MYSQL_PASSWORD: "npm"
      DB_MYSQL_NAME: "npm"
    volumes:
      - npm:/data
      - letsencrypt:/etc/letsencrypt
    restart: unless-stopped
    depends_on:
      - mariadb

  duckdns:
    image: 'linuxserver/duckdns:latest'
    container_name: duckdns
    networks:
      backend:
    hostname: duckdns
    environment:
      - PUID=1000 #optional
      - PGID=1000 #optional
      - TZ=America/Caracas
      - SUBDOMAINS=donelias1,donelias2,donelias3,donelias4,donelias5
      - TOKEN=473fba06-f1d5-4dc8-850d-e0fbba0748f4
    volumes:
      - duckdns:/config
    restart: unless-stopped
