version: '2'
volumes:
    postgres:
    erp:
    etc:
    addons:
    mariadb:
    npm:    
    letsencrypt:
    
services:
  db:
    image: postgres:13
    user: root
    environment:
      - POSTGRES_PASSWORD=erp
      - POSTGRES_USER=erp
      - POSTGRES_DB=postgres
    restart: always
    volumes:
        - postgres:/var/lib/postgresql/data

  erp:
    image: odoo:14
    user: root
    depends_on:
      - db
    ports:
      - "8069:8069"
      - "8072:8072"
    tty: true
    command: --
    environment:
      - HOST=db
      - USER=erp
      - PASSWORD=erp
    volumes:
      - erp:/var/lib/odoo
      - addons:/mnt/extra-addons
      - etc:/etc/odoo
    restart: always

  mariadb:
    image: 'jc21/mariadb-aria:latest'
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "npm"
      MYSQL_DATABASE: "npm"
      MYSQL_USER: "npm"
      MYSQL_PASSWORD: "npm"
    volumes:
      - mariadb:/var/lib/mysql
        
  npm:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "81:81"
    environment:
      DB_MYSQL_HOST: "mariadb"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "npm"
      DB_MYSQL_PASSWORD: "npm"
      DB_MYSQL_NAME: "npm"
    volumes:
      - npm:/data
      - letsencrypt:/etc/letsencrypt
    depends_on:
      - mariadb
