services:
  mariadb:
    image: 'jc21/mariadb-aria:latest'
    restart: unless-stopped
    hostname: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: 'npm'
      MYSQL_DATABASE: 'npm'
      MYSQL_USER: 'npm'
      MYSQL_PASSWORD: 'npm'
    volumes:
        - mariadb_data:/var/lib/mysql
  npm:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    hostname: npm
    ports:
      - "80:80"
      - "443:443"
      - "81:81"
    environment:
      DB_MYSQL_HOST: "mariadb"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "npm"
      DB_MYSQL_PASSWORD: "npm"
      DB_MYSQL_NAME: "npm"
    volumes:
      - npm_data:/data
      - letsencrypt_data:/etc/letsencrypt
    depends_on:
      - mariadb

  postgres:
    image: postgres:13
    user: root
    hostname: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB= "erp"
      - POSTGRES_USER= "erp"
      - POSTGRES_PASSWORD= "erp"
      - PGDATA=/var/lib/postgresql/data/   
    restart: always
    volumes:
        - postgres_data:/var/lib/postgresql/data

  erp:
    image: odoo:14
    user: root
    depends_on:
      - postgres
    hostname: erp
    ports:
      - "8069:8069"
      - "8072:8072"
    tty: true
    environment:
      - HOST= "erp"
      - USER= "erp"
      - PASSWORD= "erp"
    volumes:
      - erp_data/addons:/mnt/extra-addons
      - erp_data/etc:/etc/odoo
      - erp_data:/var/lib/odoo
    restart: always             # run as a service
    entrypoint: "/usr/bin/odoo -c /etc/odoo/odoo.conf"
