services:
  npm:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    hostname: npm
    ports:
      # These ports are in format <host-port>:<container-port>
      - '80:80' # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '81:81' # Admin Web Port
      # Add any other Stream port you want to expose
      # - '21:21' # FTP
    environment:
      DB_MYSQL_HOST: "mariadb"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "npm"
      DB_MYSQL_PASSWORD: "npm"
      DB_MYSQL_NAME: "npm"
      # Uncomment this if IPv6 is not enabled on your host
      # DISABLE_IPV6: 'true'
    volumes:
      - ./npm:/data
      - ./letsencrypt:/etc/letsencrypt
    depends_on:
      - mariadb

  mariadb:
    image: 'jc21/mariadb-aria:latest'
    restart: unless-stopped
    hostname: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: 'npm'
      MYSQL_DATABASE: 'npm'
      MYSQL_USER: 'npm'
      MYSQL_PASSWORD: 'npm'
    volumes:
        - ./mariadb/:/var/lib/mysql

  postgres:
    image: postgres:13
    user: root
    hostname: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB= postgres
      - POSTGRES_USER= erp
      - POSTGRES_PASSWORD=erp
      
      
    restart: always             # run as a service
    volumes:
        - ./postgresql:/var/lib/postgresql/data

  odoo14:
    image: odoo:14
    user: root
    depends_on:
      - postgres
    hostname: erp
    ports:
      - "8069:8069"
      - "8072:8072" # live chat
    tty: true
    command: --
#    command: odoo scaffold /mnt/extra-addons/custom_module
    environment:
      - HOST= postgres
      - USER= erp
      - PASSWORD= erp
    volumes:
      - ./erp/addons:/mnt/extra-addons
      - ./erp/etc:/etc/odoo
      - ./erp/data = /var/lib/odoo
    restart: always             # run as a service
